# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20181021_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
