# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181021_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(0, '工作人员'), (1, '消费者')], default=1),
        ),
    ]
