# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 07:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_userinfo_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='created_time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='token',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
