# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_auth.UserInfo'),
        ),
    ]
