# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20181022_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'publisher')]),
        ),
    ]
